### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/sale-workflow#346]
Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] account_invoice_reorder_lines
- [ ] mail_quotation
- [ ] partner_prepayment
- [ ] partner_prospect
- [ ] pricelist_share_companies
- [ ] product_customer_code_sale
- [ ] product_special_type
- [ ] product_special_type_invoice
- [ ] product_special_type_sale
- [x] sale_automatic_workflow - @lasley - #391 
- [ ] sale_automatic_workflow_payment_mode - By @lmignon - #471 
- [x] sale_cancel_reason - By @kittiu - #477 
- [ ] sale_condition_text
- [ ] sale_delivery_term
- [ ] sale_dropshipping
- [x] sale_exception - @mourad-ehm  https://github.com/OCA/sale-workflow/pull/409
- [ ] sale_exception_nostock
- [ ] sale_fiscal_position_update
- [ ] sale_jit_on_services
- [ ] sale_last_price_info
- [ ] sale_multi_picking
- [ ] sale_order_add_variants
- [x] ~~sale_order_back2draft~~ - Already on core - Removed on #405 
- [ ] sale_order_force_number
- [x] sale_order_line_description - By @SimoRubi - #530 
- [x] ~~sale_order_line_variant_description~~ - By @angedras - #462 Move to OCA/product-variant
- [x] sale_order_lot_selection - By @mourad-ehm - #412 
- [x] sale_order_price_recalculation - By @chienandalu - #506 
- [ ] sale_order_revision - By @JayVora-SerpentCS - #396
- [x] sale_order_type - By @PierreFaniel - #390 
- [x] sale_owner_stock_sourcing - By @Cedric-Pigeon - #483 
- [ ] sale_packaging_price - By @grauschnabel - #564 
- [x] sale_partner_incoterm - By @lbelorgey - #778 
- [x] ~~sale_partner_order_policy~~ - Included in core - By @alexis-via - #609 
- [ ] sale_payment_term_interest
- [ ] sale_procurement_group_by_line  - By @mreficent - #498
- [x] sale_product_set - By @leemand - #379 
- [x] sale_product_set_layout - By @leemannd - #380 
- [ ] sale_revert_done - @stefanrijnhart - #577
- [ ] sale_quotation_number
- [ ] sale_quotation_sourcing
- [ ] sale_quotation_sourcing_stock_route_transit
- [ ] sale_reason_to_export
- [x] sale_rental - By @SodexisTeam - #357 
- [x] sale_sourced_by_line - By @mreficent - #515 
- [ ] sale_sourced_by_line_sale_transport_multi_address
- [x] sale_start_end_dates - By @SodexisTeam - #357 
- [ ] sale_stock_global_delivery_lead_time
- [ ] sale_validity

**Comment by SodexisTeam** [comment]
For info, we are migrating sale_rental and sale_start_end_dates

**Comment by pedrobaeza** [comment]
OK, written in the main comment.

**Comment by augustosamame** [comment]
@darshan-serpent is there a public repository where we can follow your progress on sale_sourced_by_line migration to v10?

**Comment by pedrobaeza** [comment]
That module is not yet migrated nor planned

**Comment by augustosamame** [comment]
Hi Pedro. In the list of modules to migrate, you indicate: 
sale_sourced_by_line => @darshan-serpent is working on it

**Comment by pedrobaeza** [comment]
Oh, sorry, I didn't see that, because there's no comment, but directly written.

**Comment by leemannd** [comment]
Hello, there is also sale_product_set_layout https://github.com/OCA/sale-workflow/pull/380 .

**Comment by lasley** [comment]
sale_automatic_workflow - #391

**Comment by angedras** [comment]
migrating sale_order_line_variant_description from 8.0 to 10.0

**Comment by lmignon** [comment]
sale_automatic_workflow_payment_mode #471

**Comment by kittiu** [comment]
sale_cancel_reason #477

**Comment by blutecsolutions** [comment]
Can we have a migration for:
sale_order_price_recalculation

?

**Comment by pedrobaeza** [comment]
Do you want to make the migration or are you asking if someone is going to migrate the module?

**Comment by berpweb** [comment]
@darshan-serpent Hi, do we have an update regarding the module `sale_sourced_by_line` that you guys are working on?

**Comment by msadiq1411** [comment]
Is anyone migrating: v8. `sale_line_quantity_properties_based`  to v10.0?

**Comment by pedrobaeza** [comment]
It doesn't seem so, but properties are removed in v10, so I don't think it can be migrated.

**Comment by msadiq1411** [comment]
Ok is there anything similar out there, in the app market ?

**Comment by pedrobaeza** [comment]
Check it out yourself. I'm not aware of anything outside OCA.

**Comment by SimoRubi** [comment]
Hi,
I'm working on the migration of module [sale_order_line_description](https://github.com/OCA/sale-workflow/tree/8.0/sale_order_line_description)

**Comment by pedrobaeza** [comment]
OK, noted

**Comment by SimoRubi** [comment]
Hi,
I've migrated the module [sale_quotation_number](https://github.com/OCA/sale-workflow/tree/8.0/sale_quotation_number) in #591, please close old PR #518.
Thanks

**Comment by FFernandez-PlanetaTIC** [comment]
product_margin_classification #909
