### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/sale-workflow#538]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_invoice_reorder_lines
- [ ] mail_quotation
- [ ] partner_prepayment
- [x] partner_prospect - By @oihane - #550 
- [ ] pricelist_share_companies
- [ ] product_customer_code_sale
- [ ] product_special_type - By @HirenDangar - #902 
- [ ] product_special_type_invoice
- [ ] product_special_type_sale
- [x] product_supplierinfo_for_customer_sale - By @xavierjimenez - #681 
- [x] sale_automatic_workflow - By @gdgellatly - #581 
- [ ] sale_automatic_workflow_exception
- [x] sale_automatic_workflow_payment_mode - By @hugosantosred - #608 
- [ ] sale_cancel_reason - ~~By @sudhir-serpentcs - #559~~
- [x] sale_commercial_partner - By @Swapnesh-SerpentCS - #606 
- [ ] sale_condition_text
- [ ] sale_delivery_term
- [ ] sale_dropshipping
- [x] sale_exception - By @simahawk - #576
- [ ] sale_exception_nostock
- [x] ~~sale_fiscal_position_update~~ Included in core
- [x] sale_force_invoiced - ~~By @andreasdsp - #649~~ By @mreficent - #688 
- [x] sale_invoice_group_method - By @rgarnau - #568
- [ ] sale_isolated_quotation - By @rsullivan2704 - #708
- [ ] sale_jit_on_services
- [x] sale_last_price_info - By @Swapnesh-SerpentCS - #603 
- [ ] sale_layout_hidden
- [x] sale_merge_draft_invoice - By @rgarnau - #569
- [ ] sale_mrp_link - By @NachoAlesLopez - #1031 
- [ ] sale_multi_picking
- [x] sale_order_action_invoice_create_hook - By @rgarnau - #567
- [x] sale_order_digitized_signature - By @cubells - #854 
- [ ] sale_order_force_number
- [x] sale_order_invoicing_finished_task - By @carlosdauden - #626 
- [x] sale_order_line_date - By @OpenCode - #600
- [x] sale_order_line_description - By @cubells - #759 
- [x] sale_order_line_sequence - By @remihb - #724 
- [ ] sale_order_lot_generator
- [ ] sale_order_lot_mrp
- [ ] sale_order_lot_selection - ~~By @OpenCode - #628~~ By @mgosai - #714
- [ ] sale_order_margin_percent - ~~By OmniaGit - #692~~
- [x] sale_order_price_recalculation - By @novawish - #584 
- [x] sale_order_product_recommendation - By @chienandalu - #670
- [x] sale_order_revision - By @devang-dreambits - #679 
- [x] sale_order_type - By @chienandalu - #619 
- [ ] sale_owner_stock_sourcing
- [ ] sale_packaging_price
- [ ] sale_payment_term_interest
- [x] sale_procurement_group_by_line - By @mreficent - #758
- [x] sale_product_set - By @simahawk - #574
- [ ] sale_product_set_layout
- [x] sale_quotation_number - By @murtuzasaleh - #665 
- [ ] sale_quotation_sourcing
- [ ] sale_quotation_sourcing_stock_route_transit
- [ ] sale_reason_to_export
- [ ] sale_rental - By @danhvophuong - #819 
- [ ] sale_sourced_by_line - By @AaronHForgeFlow - #1927
- [ ] sale_sourced_by_line_sale_transport_multi_address
- [x] sale_start_end_dates - By @murtuzasaleh - #669 
- [ ] sale_stock_global_delivery_lead_time
- [x] sale_stock_picking_blocking - By @mreficent - #733 
- [ ] sale_stock_picking_blocking_proc_group_by_line - By @mreficent - #736
- [ ] sale_triple_discount - By @xavierjimenez - #627
- [x] sale_validity - By @murtuzasaleh - #666 
- [x] sales_team_security - By @pedrobaeza - #732

**Comment by oihane** [comment]
partner_prospect https://github.com/OCA/sale-workflow/pull/550

**Comment by simahawk** [comment]
sale_product_set @simahawk #574

**Comment by simahawk** [comment]
sale_exception @simahawk #576

**Comment by OpenCode** [comment]
sale_order_line_date https://github.com/OCA/sale-workflow/pull/600

**Comment by JayVora-SerpentCS** [comment]
sale_commercial_partner #606

**Comment by hugosantosred** [comment]
sale_automatic_workflow_payment_mode #608

**Comment by RoelAdriaans** [comment]
sale_fiscal_position_update - Not needed since https://github.com/odoo/odoo/blob/6c6c4b89a077d2345425771c854ac608ff4f136d/addons/sale/models/sale.py#L107-L113

**Comment by JuaniFreedoo** [comment]
sale_order_revision #664

**Comment by murtuzasaleh** [comment]
sale_quotation_number https://github.com/OCA/sale-workflow/pull/665

**Comment by murtuzasaleh** [comment]
sale_validity https://github.com/OCA/sale-workflow/pull/666

**Comment by murtuzasaleh** [comment]
sale_triple_discount https://github.com/OCA/sale-workflow/pull/667

**Comment by murtuzasaleh** [comment]
sale_start_end_dates https://github.com/OCA/sale-workflow/pull/669

**Comment by murtuzasaleh** [comment]
sale_procurement_group_by_line https://github.com/OCA/sale-workflow/pull/673

**Comment by VRodrigo** [comment]
sale_order_add_variants #678

**Comment by devang-dreambits** [comment]
Hello all,

I'm migrating sale_order_revision module to v11 with PR #679

**Comment by ShuP1** [comment]
Is sale_rental ready for v11 ? or migration planed ? @alexis-via

**Comment by ray-odoo** [comment]
Tried to install **sale_order_line_sequence** on a new v11 odoo.sh database today, without any changes from the v10 version.

Passed all automated odoo.sh tests.  

Functionally it worked when I switched the sequence of lines on an existing SO with two lines and created a new SO and switched the lines before saving.

Turning over to my User for UAT.

UPDATE:  9/8/18. Fatal error when trying to print a Sale Order:

I believe this to be related to a database specific customization.  Commenting out the report view change resolves this - and client doesn't want sequence show on the report anyway.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, check partner_prospect - By @oihane - #550 because it is already merged

sale_force_invoiced - By @andreasdsp - #649 is merged in #688 

Please, add to the list sale_invoice_group_method - By @rgarnau - #568 that is already migrated and merged

Please check sale_last_price_info - By @Swapnesh-SerpentCS - #603 because it is already merged

Please, add to the list sale_merge_draft_invoice - By @rgarnau - #569 that is already migrated and merged

Please, add to the list sale_order_action_invoice_create_hook - By @rgarnau - #567 that is already migrated and merged

Please, add to the list sale_order_line_date - By @OpenCode - #600 that is already migrated and merged

Please check sale_order_line_sequence - By @remihb - #724 because it is already merged

Please, add to the list sale_order_product_recommendation - By @chienandalu - #670 that is already migrated and merged

Please, add to the list sale_start_end_dates - By @murtuzasaleh - #669 that is already migrated and merged

Please, add to the list sales_team_security - By @pedrobaeza - #732 that is already migrated and merged

There is a PR for sale_procurement_group_by_line - By @mreficent - #758 that is alredy approved and waiting to be merged

Please, add to the list sale_stock_picking_blocking_proc_group_by_line - By @mreficent - #736 that is already migrated and merged

sale_order_lot_selection - By @OpenCode - #628 is closed and there is other PR - By @mgosai - #714 

There is a PR for the migration of sale_isolated_quotation - By @rsullivan2704 - #708 

There is a PR for the migration of sale_order_margin_percent - By OmniaGit - #692 

There is a PR for the migration of sale_procurement_group_by_line - By @murtuzasaleh - #673 

There is a PR for the migration of sale_triple_discount - By @xavierjimenez - #627

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please uncheck sale_stock_picking_blocking_proc_group_by_line - By @mreficent - #736
My fault, it wasn't merged:
> Please, add to the list sale_stock_picking_blocking_proc_group_by_line - By @mreficent - #736 that is already migrated and merged

**Comment by ghost** [comment]
sale_rental [#819](https://github.com/OCA/sale-workflow/pull/819)

**Comment by emagdalenaC2i** [comment]
sale_cancel_reason - By @sudhir-serpentcs - #559 is closed

sale_order_digitized_signature - By @cubells - #828 is closed and superseed in #854 

sale_order_margin_percent - By OmniaGit - #692 is closed

**Comment by nikul-serpentcs** [comment]
product_special_type -> #902

**Comment by NachoAlesLopez** [comment]
sale_mrp_link: #1031

**Comment by rafaelbn** [comment]
sale_sourced_by_line: https://github.com/OCA/sale-workflow/pull/1927 by @AaronHForgeFlow 

https://github.com/OCA/sale-workflow/pull/1927#issuecomment-1047182213
